package ru.mipt1c.laboratory.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import ru.mipt1c.laboratory.db.dto.ConfigPropertyCondition;
import ru.mipt1c.laboratory.db.dto.ConfigPropertyDto;

@Component
public interface ConfigPropertyDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_property
     *
     * @mbggenerated
     */
    int countByExample(ConfigPropertyCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_property
     *
     * @mbggenerated
     */
    int deleteByExample(ConfigPropertyCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_property
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer propertyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_property
     *
     * @mbggenerated
     */
    int insert(ConfigPropertyDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_property
     *
     * @mbggenerated
     */
    int insertSelective(ConfigPropertyDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_property
     *
     * @mbggenerated
     */
    List<ConfigPropertyDto> selectByExample(ConfigPropertyCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_property
     *
     * @mbggenerated
     */
    ConfigPropertyDto selectByPrimaryKey(Integer propertyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_property
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ConfigPropertyDto record, @Param("example") ConfigPropertyCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_property
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ConfigPropertyDto record, @Param("example") ConfigPropertyCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_property
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ConfigPropertyDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_property
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ConfigPropertyDto record);

    /**
     * Custom generated method to insert list.
     * @mbggenerated
     */
    void insertList(@Param("recordList") List<ConfigPropertyDto> values);
}