package ru.mipt1c.laboratory.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import ru.mipt1c.laboratory.db.dto.GaussExperimentFilesCondition;
import ru.mipt1c.laboratory.db.dto.GaussExperimentFilesDto;

@Component
public interface GaussExperimentFilesDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gauss_experiment_files
     *
     * @mbggenerated
     */
    int countByExample(GaussExperimentFilesCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gauss_experiment_files
     *
     * @mbggenerated
     */
    int deleteByExample(GaussExperimentFilesCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gauss_experiment_files
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gauss_experiment_files
     *
     * @mbggenerated
     */
    int insert(GaussExperimentFilesDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gauss_experiment_files
     *
     * @mbggenerated
     */
    int insertSelective(GaussExperimentFilesDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gauss_experiment_files
     *
     * @mbggenerated
     */
    List<GaussExperimentFilesDto> selectByExample(GaussExperimentFilesCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gauss_experiment_files
     *
     * @mbggenerated
     */
    GaussExperimentFilesDto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gauss_experiment_files
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GaussExperimentFilesDto record, @Param("example") GaussExperimentFilesCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gauss_experiment_files
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GaussExperimentFilesDto record, @Param("example") GaussExperimentFilesCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gauss_experiment_files
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GaussExperimentFilesDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gauss_experiment_files
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GaussExperimentFilesDto record);

    /**
     * Custom generated method to insert list.
     * @mbggenerated
     */
    void insertList(@Param("recordList") List<GaussExperimentFilesDto> values);
}