package ru.mipt1c.laboratory.db.dto;

public class ConfigPropertyDto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_property.property_id
     *
     * @mbggenerated
     */
    private Integer propertyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_property.property_name
     *
     * @mbggenerated
     */
    private String propertyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_property.property_value
     *
     * @mbggenerated
     */
    private String propertyValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_property.property_description
     *
     * @mbggenerated
     */
    private String propertyDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_property.property_id
     *
     * @return the value of config_property.property_id
     *
     * @mbggenerated
     */
    public Integer getPropertyId() {
        return propertyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_property.property_id
     *
     * @param propertyId the value for config_property.property_id
     *
     * @mbggenerated
     */
    public void setPropertyId(Integer propertyId) {
        this.propertyId = propertyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_property.property_name
     *
     * @return the value of config_property.property_name
     *
     * @mbggenerated
     */
    public String getPropertyName() {
        return propertyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_property.property_name
     *
     * @param propertyName the value for config_property.property_name
     *
     * @mbggenerated
     */
    public void setPropertyName(String propertyName) {
        this.propertyName = propertyName == null ? null : propertyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_property.property_value
     *
     * @return the value of config_property.property_value
     *
     * @mbggenerated
     */
    public String getPropertyValue() {
        return propertyValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_property.property_value
     *
     * @param propertyValue the value for config_property.property_value
     *
     * @mbggenerated
     */
    public void setPropertyValue(String propertyValue) {
        this.propertyValue = propertyValue == null ? null : propertyValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_property.property_description
     *
     * @return the value of config_property.property_description
     *
     * @mbggenerated
     */
    public String getPropertyDescription() {
        return propertyDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_property.property_description
     *
     * @param propertyDescription the value for config_property.property_description
     *
     * @mbggenerated
     */
    public void setPropertyDescription(String propertyDescription) {
        this.propertyDescription = propertyDescription == null ? null : propertyDescription.trim();
    }
}