package ru.mipt1c.laboratory.db.dto;

public class GaussExperimentFilesDto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gauss_experiment_files.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gauss_experiment_files.access
     *
     * @mbggenerated
     */
    private Integer access;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gauss_experiment_files.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gauss_experiment_files.userId
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gauss_experiment_files.id
     *
     * @return the value of gauss_experiment_files.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gauss_experiment_files.id
     *
     * @param id the value for gauss_experiment_files.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gauss_experiment_files.access
     *
     * @return the value of gauss_experiment_files.access
     *
     * @mbggenerated
     */
    public Integer getAccess() {
        return access;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gauss_experiment_files.access
     *
     * @param access the value for gauss_experiment_files.access
     *
     * @mbggenerated
     */
    public void setAccess(Integer access) {
        this.access = access;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gauss_experiment_files.name
     *
     * @return the value of gauss_experiment_files.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gauss_experiment_files.name
     *
     * @param name the value for gauss_experiment_files.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gauss_experiment_files.userId
     *
     * @return the value of gauss_experiment_files.userId
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gauss_experiment_files.userId
     *
     * @param userid the value for gauss_experiment_files.userId
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
}